zad_2/WebApplication4/WebApplication4/Models/Employee.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication4.Models
{
    public class Employee
    {
        public int Id { get; set; }

        [Required]
        [StringLength(20, MinimumLength = 3)]
        public string FirstName { get; set; }//ім'я
        
        [Required]
        [StringLength(30, MinimumLength = 3)]
        public string LastName { get; set; }//прізвище

        [Required]
        [DataType(DataType.Date)]
        public DateTime DenNarodg { get; set; }

        
        [Required]
        [Range(1, double.MaxValue, ErrorMessage = "Зарплата має бути більшою за 0.")]
        public double Zarplata { get; set; }
    }
}

zad_2/WebApplication4/WebApplication4/Models/ErrorViewModel.cs
namespace WebApplication4.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

zad_2/WebApplication4/WebApplication4/Models/Manager.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication4.Models
{
    public class Manager : Employee
    {
        [Range(0, int.MaxValue, ErrorMessage = "Кількість підлеглих має бути більша або рівна 0.")]
        public int EmployeeCount { get; set; } // Кількість підлеглих
    }
}

zad_2/WebApplication4/WebApplication4/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication4.Data;
using WebApplication4.Models;

namespace WebApplication4.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IDataService _dataService;

        public EmployeeController(IDataService dataService)
        {
            _dataService = dataService;
        }

        // Страница для создания работника
        public IActionResult Create()
        {
            return View();
        }
        // Обработка формы для добавления работеика
        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Create(Employee employee)
        {
            //var existingEmployee = _dataService.GetEmployees().FirstOrDefault(e => e.FirstName == employee.FirstName
            //  && e.LastName == employee.LastName && e.DenNarodg==employee.DenNarodg);
            var existingEmployee = _dataService.GetEmployees()
    .FirstOrDefault(e => string.Equals(e.FirstName, employee.FirstName, StringComparison.Ordinal) &&
                         string.Equals(e.LastName, employee.LastName, StringComparison.Ordinal)
                         && e.DenNarodg == employee.DenNarodg);

            if (existingEmployee != null)
            {
                // Добавляем сообщение в TempData
                TempData["ErrorMessage"] = "Такий робітник вже існує в базі.";

                // Возвращаем представление с текущими данными работника
                return View(employee);
            }

            var existingManager = _dataService.GetManagers()
    .FirstOrDefault(m => string.Equals(m.FirstName, employee.FirstName, StringComparison.Ordinal) &&
                         string.Equals(m.LastName, employee.LastName, StringComparison.Ordinal)
                         && m.DenNarodg == employee.DenNarodg);

            if (existingManager != null)
            {
                // Добавляем сообщение в TempData
                TempData["ErrorMessage"] = $"{employee.FirstName} {employee.LastName} вже записаний в базі як менеджер.";
                return View(employee);
            }


            // Если данные валидны, добавляем работника
            if (ModelState.IsValid)
            {
                employee.Id = _dataService.GetEmployees().Count + 1;
                _dataService.AddEmployee(employee);
                return RedirectToAction(nameof(Index));
            }

            return View(employee);
        }



        public IActionResult Index()
        {
            // Получаем список сотрудников из общего сервиса
            var employees = _dataService.GetEmployees();
            return View(employees);
        }
    }

    

}

zad_2/WebApplication4/WebApplication4/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication4.Models;

namespace WebApplication4.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

zad_2/WebApplication4/WebApplication4/Controllers/ManagerController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication4.Data;
using WebApplication4.Models;

namespace WebApplication4.Controllers
{
    public class ManagerController : Controller
    {
        private readonly IDataService _dataService;

        // Внедрение IDataService через конструктор
        public ManagerController(IDataService dataService)
        {
            _dataService = dataService;
        }

        // Страница для создания менеджера
        public IActionResult Create()
        {
            return View();
        }
        // Обработка формы для добавления менеджера
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Manager manager)
        {
            // Проверка на существующего менеджера
            //var existingManager = _dataService.GetManagers().FirstOrDefault(e => e.FirstName == manager.FirstName
            //    && e.LastName == manager.LastName && e.DenNarodg == manager.DenNarodg);
            var existingManager = _dataService.GetManagers()
    .FirstOrDefault(e => string.Equals(e.FirstName, manager.FirstName, StringComparison.Ordinal) &&
                         string.Equals(e.LastName, manager.LastName, StringComparison.Ordinal)
                         && e.DenNarodg == manager.DenNarodg);

            if (existingManager != null)
            {
                // Добавляем сообщение в TempData
                TempData["ErrorMessage"] = "Такий менеджер вже існує в базі.";
                return View(manager);
            }

            // Получаем список сотрудников из сервиса
            var employees = _dataService.GetEmployees();

            /*var existingEmployee = _dataService.GetEmployees().FirstOrDefault(e => e.FirstName == 
            manager.FirstName  && e.LastName == manager.LastName && e.DenNarodg == manager.DenNarodg); */
            var existingEmployee = _dataService.GetEmployees()
    .FirstOrDefault(e => string.Equals(e.FirstName, manager.FirstName, StringComparison.Ordinal) &&
                         string.Equals(e.LastName, manager.LastName, StringComparison.Ordinal)
                         && e.DenNarodg == manager.DenNarodg);

            int totalEmployees = employees.Count;  // Общее количество работников
            int subordinatesCount = manager.EmployeeCount;  // Количество подчиненных у менеджера

            if (existingEmployee != null)
            {
                // Добавляем сообщение в TempData
                TempData["ErrorMessage"] = $"{manager.FirstName} {manager.LastName} вже записаний в базі як робітник.";
                return View(manager);
            }


            // Проверка, чтобы количество подчиненных не превышало количество работников
            if (subordinatesCount > totalEmployees)
            {
                TempData["ErrorMessage"] = "Менеджер не може мати більше підлеглих, ніж є робітників.";
                return View(manager);
            }

            // Если данные валидны, добавляем менеджера
            if (ModelState.IsValid)
            {
                manager.Id = _dataService.GetManagers().Count + 1;
                _dataService.AddManager(manager);  // Добавляем менеджера через сервис
                return RedirectToAction(nameof(Index));
            }

            return View(manager);
        }

        // Метод для отображения списка менеджеров
        public IActionResult Index()
        {
            // Получаем список менеджеров из общего сервиса
            var managers = _dataService.GetManagers();
            return View(managers);
        }
    }
}

zad_2/WebApplication4/WebApplication4/Views/Employee/Create.cshtml
@model WebApplication4.Models.Employee

@{
    var errorMessage = TempData["ErrorMessage"] as string;
}

@if (!string.IsNullOrEmpty(errorMessage))
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        @errorMessage
        <button type="button" class="close" data-dismiss="alert" aria-label="Close" onclick="pysto()" >
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}


<h2>Додати нового робітника</h2>

<form asp-action="Create" method="post">
    <div >
        <label>Ім'я</label>
        <input type="text" asp-for="FirstName" class="form-control" />
        
    </div>

    <div >
        <label >Прізвище</label>
        <input type="text" asp-for="LastName" class="form-control" />
    </div>

    <div >
        <label >Дата народження</label>
        <input type="date" asp-for="DenNarodg" class="form-control" />
    </div>

    <div >
        <label >Зарплата</label>
        <input type="number" asp-for="Zarplata" class="form-control" />    
    </div>

    <button type="submit" class="btn btn-primary">Додати</button>
</form>

<a href="@Url.Action("Index", "Employee")">Повернутися до списку робітників</a>

<script>
    function pysto() {
        document.location.href = "Create";
    }
</script>

zad_2/WebApplication4/WebApplication4/Views/Employee/Index.cshtml
@model IEnumerable<WebApplication4.Models.Employee>
@{
}

<h2>Список робітників</h2>
<a href="@Url.Action("Create", "Employee")">Додати робітника</a>
<a href="@Url.Action("Index", "Manager")" style="margin-left: 50px;">Список менеджерів</a>
<table class="table">
    <thead>
        <tr>
            <th>Ім'я</th>
            <th>Прізвище</th>
            <th>Дата народження</th>
            <th>Заробітна плата</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var employee in Model)
        {
            <tr>
                <td>@employee.FirstName</td>
                <td>@employee.LastName</td>
                <td>@employee.DenNarodg.Date.ToString("yyyy-MM-dd")</td>
                <td>@employee.Zarplata</td>
            </tr>
        }
    </tbody>
</table>

zad_2/WebApplication4/WebApplication4/Views/Manager/Create.cshtml
@model WebApplication4.Models.Manager

@{
    var errorMessage = TempData["ErrorMessage"] as string;
}

@if (!string.IsNullOrEmpty(errorMessage))
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        @errorMessage
        <button type="button" class="close" data-dismiss="alert" aria-label="Close" onclick="pysto()">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}



<h2>Додати нового менеджера</h2>

<form asp-action="Create" method="post">
    <div>
        <label>Ім'я</label>
        <input type="text" asp-for="FirstName" class="form-control" />

    </div>

    <div>
        <label>Прізвище</label>
        <input type="text" asp-for="LastName" class="form-control" />
    </div>

    <div>
        <label>Дата народження</label>
        <input type="date" asp-for="DenNarodg" class="form-control" />
    </div>

    <div>
        <label>Кількість підлеглих</label>
        <input type="number" asp-for="EmployeeCount" class="form-control" />
    </div>

    <div>
        <label>Зарплата</label>
        <input type="number" asp-for="Zarplata" class="form-control" />
    </div>

    <button type="submit" class="btn btn-primary">Додати</button>
</form>

<a href="@Url.Action("Index", "Manager")">Повернутися до списку менеджерів</a>

<script>
    function pysto() {
        document.location.href = "Create";
    }
</script>

zad_2/WebApplication4/WebApplication4/Views/Manager/Index.cshtml
@model IEnumerable<WebApplication4.Models.Manager>
@{
}

<h2>Список менеджерів</h2>
<a href="@Url.Action("Create", "Manager")">Додати менеджера</a>
<a href="@Url.Action("Index", "Employee")" style="margin-left: 50px;">Список робітників</a>
<table class="table">
    <thead>
        <tr>
            <th>Ім'я</th>
            <th>Прізвище</th>
            <th>Дата народження</th>
            <th>Кільк.підлеглих</th>
            <th>Заробітна плата</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var employee in Model)
        {
            <tr>
                <td>@employee.FirstName</td>
                <td>@employee.LastName</td>
                <td>@employee.DenNarodg.Date.ToString("yyyy-MM-dd")</td>
                <td>@employee.EmployeeCount</td>
                <td>@employee.Zarplata</td>
            </tr>
        }
    </tbody>
</table>

zad_2/WebApplication4/WebApplication4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication4</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication4.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication4</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebApplication4 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>