zad_3/WebApplication7/WebApplication7/Models/Book.cs
namespace WebApplication7.Models
{
    public class Book
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public decimal Price { get; set; }
        public int Pages { get; set; }

        public DateTime DateTime { get; set; }//дата випуску

        
        // Зв'язок з автором
        public int AuthorId { get; set; }
        public Author Author { get; set; }

        //Зв'язок з жанром
        public int GanrId { get; set; }
        
        public Ganr Ganr { get; set; }
    }


}

zad_3/WebApplication7/WebApplication7/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication7.Data;
using WebApplication7.Models;
using static System.Reflection.Metadata.BlobBuilder;


namespace WebApplication7.Controllers
{
    public class BookController : Controller
    {
        private readonly IDataService _repository;

        public BookController(IDataService repository)
        {
            _repository = repository;
        }

        // Виведення усіх книг
        public IActionResult Index(string searchString)
        {
            var books = string.IsNullOrEmpty(searchString)
                ? _repository.GetBooks()
                : _repository.SearchBooks(searchString);

            ViewBag.SearchMessage = string.IsNullOrEmpty(searchString)
                ? "Список книг"
                : $"{searchString}";

            return View(books);
        }


        // Додавання нової книги
        public IActionResult Create()
        {
            ViewData["Authors"] = _repository.GetAuthors();
            ViewData["Ganr"] = _repository.GetGanrs();  // Додаємо жанри
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Book book)
        {
            // Перевіряємо, чи існує книга
            var existingBook = _repository.GetBooks().FirstOrDefault(b => b.Title.Equals(book.Title, StringComparison.OrdinalIgnoreCase) 
            && b.AuthorId==book.AuthorId);

            if (existingBook != null)
            {
                TempData["SearchMessage1"] = "Така книга вже є";
            }
            else
            {
                book.Author = _repository.GetAuthors().FirstOrDefault(a => a.Id == book.AuthorId);
                book.Ganr = _repository.GetGanrs().FirstOrDefault(g => g.Id == book.GanrId);

                _repository.AddBook(book);
            }
            
            return RedirectToAction(nameof(Index));
            
        }

        // Видалення книги
        public IActionResult Delete(int id, string temp="0")
        {
            var book = _repository.GetBooks().FirstOrDefault(b => b.Id == id);

            if (book != null)
            {
                ViewBag.SearchMessage = temp;
                return View(book);
            }

            return NotFound();
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var book = _repository.GetBooks().FirstOrDefault(b => b.Id == id);
            if (book != null)
            {
                _repository.DeleteBook(id);
                return RedirectToAction(nameof(Index));
            }

            TempData["SearchMessage1"] = "Книгу не знайдено";
            return RedirectToAction(nameof(Index));
        }

        // Редагування книги
        public IActionResult Edit(int id)
        {
            var book = _repository.GetBooks().FirstOrDefault(b => b.Id == id);
            
            ViewData["Authors"] = _repository.GetAuthors();
            ViewData["Ganr"] = _repository.GetGanrs();
            return View(book);
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Book book, string OldTitle)
        {
            var existingBook = _repository.GetBooks().FirstOrDefault(b =>b.Id == id);
            if (existingBook == null)
            {
                TempData["SearchMessage1"] = "Книга була видалена раніше";
                return RedirectToAction(nameof(Index));
            }

            existingBook = _repository.GetBooks().FirstOrDefault(b => b.Title.Equals(OldTitle, StringComparison.OrdinalIgnoreCase)
            );
            if (existingBook == null)
            {
                TempData["SearchMessage1"] = "Книга була редагована раніше";
                return RedirectToAction(nameof(Index));
            }

            // Перевіряємо, чи існує книга
            existingBook = _repository.GetBooks().FirstOrDefault(b => b.Title.Equals(book.Title, StringComparison.OrdinalIgnoreCase)
            && b.AuthorId == book.AuthorId && id!=b.Id);

            if (existingBook != null)
            {
                TempData["SearchMessage1"] = "Така книга вже є";
            }
            else
            {
                book.Author = _repository.GetAuthors().FirstOrDefault(a => a.Id == book.AuthorId);
                book.Ganr = _repository.GetGanrs().FirstOrDefault(g => g.Id == book.GanrId);
                _repository.EditBook(book);
            }
        
            return RedirectToAction(nameof(Index));
        }
    }
}

zad_3/WebApplication7/WebApplication7/Views/Book/Create.cshtml
@model Book

<h2>Додати книгу</h2>
<a href="@Url.Action("Index", "Book")">Список книг</a>
<form asp-action="Create" method="post">
    <table class="table">
        <th>Назва</th>
        <th>Автор</th>
        <th>Жанр</th>
        <th>Дата виходу</th>
        <th>Ціна</th>
        <th>Кільк.сторінок</th>
        <tbody>
            <tr>
                <td><input type="text" required asp-for="Title" /></td>
                <td>
                    <select name="AuthorId" required>
                        @foreach (var author in ViewData["Authors"] as List<Author>)
                        {
                            <option value="@author.Id" asp-for="AuthorId">@author.Name</option>
                        }
                    </select>
                </td>
                <td>
                    <select name="GanrId" required>
                        @foreach (var ganr in ViewData["Ganr"] as List<Ganr>)
                        {
                            <option value="@ganr.Id" asp-for="GanrId">@ganr.Name</option>
                        }
                    </select>

                </td>
                <td><input type="date" asp-for="DateTime" required />
                <td><input type="number" required asp-for="Price" /></td>
                <td><input type="number" required asp-for="Pages" /></td>

            </tr>
        </tbody>
    </table>

    <button class="btn btn-success" type="submit">Save Book</button>
</form>

zad_3/WebApplication7/WebApplication7/Views/Book/Delete.cshtml
@model Book

<h3>Ви дійсно хочете видалити книгу: @Model.Title?</h3>

<form method="post" asp-action="Delete">
    <button type="submit" class="btn btn-danger">Yes, Delete</button>
</form>

</br>

@{
    var qqq = string.Equals(ViewBag.SearchMessage, "Список книг", StringComparison.Ordinal);
    if (!qqq)
    {
        <a href="@Url.Action("Index", "Book",new { searchString =@ViewBag.SearchMessage})">Cancel</a>
    }
    else
    {
        int q = 1;
        <a href="@Url.Action("Index", "Book")">Cancel</a>
    }
}

zad_3/WebApplication7/WebApplication7/Views/Book/Edit.cshtml
@model Book

<h2>Редагування книги</h2>
<a href="@Url.Action("Index", "Book")">Список книг</a>

<form asp-action="Edit" method="post">
    <input type="hidden" name="OldTitle" value="@Model.Title" />

    <table class="table">
        <th>Назва</th>
        <th>Автор</th>
        <th>Жанр</th>
        <th>Дата виходу</th>
        <th>Ціна</th>
        <th>Кільк.сторінок</th>
        <tbody>
            <tr>
                <td><input type="text" required asp-for="Title" /></td>
                <td>
                    <select name="AuthorId" required>
                        @foreach (var author in ViewData["Authors"] as List<Author>)
                        {
                            <option value="@author.Id" asp-for="AuthorId">@author.Name</option>
                        }
                    </select>
                </td>
                <td>
                    <select name="GanrId" required>
                        @foreach (var ganr in ViewData["Ganr"] as List<Ganr>)
                        {
                            <option value="@ganr.Id" asp-for="GanrId">@ganr.Name</option>
                        }
                    </select>

                </td>
                <td><input type="date" asp-for="DateTime" required />
                <td><input type="number" required asp-for="Price" /></td>
                <td><input type="number" required asp-for="Pages" /></td>
                
            </tr>
        </tbody>
    </table>

    <button class="btn btn-success" type="submit">Save Book</button>
</form>

zad_3/WebApplication7/WebApplication7/Views/Book/Index.cshtml
@model IEnumerable<WebApplication7.Models.Book>
@{
    string q,q1;
    var qqq1 = string.Equals(ViewBag.SearchMessage, "Список книг", StringComparison.Ordinal);
    if (!qqq1)
    {
        q = $"Результати пошуку за запитом: \"{ViewBag.SearchMessage}\"";
        
            <h2>@q</h2>
        <a href="@Url.Action("Index", "Book")">Список книг</a>
    }
    else
    {
        q = ViewBag.SearchMessage;

            <form method="get" action="@Url.Action("Index", "Book")" style="display: flex; align-items: center;">
                <h2>@q</h2>
                <input type="text" name="searchString" placeholder="Search books..." style="margin-left:50px" />
                <button type="submit">Search</button>
            </form>

            <a href="@Url.Action("Create", "Book")">Додати книгу</a>
            <a href="@Url.Action("CreateAuthor", "Author")" style="margin-left: 20px">Додати автора</a>
    }

    // Перевірка, чи є повідомлення в TempData якщо файла не існує
    if (TempData["SearchMessage1"] != null)
    {
        var searchMessage1 = TempData["SearchMessage1"].ToString();
        <script>
            alert(@Json.Serialize(searchMessage1));
        </script>
    }

}

<table class="table table-bordered table-striped" style="margin-top:10px;">
    <thead>
        <tr>
            <th>Назва</th>
            <th>Автор</th>
            <th>Жанр</th>
            <th>Дата виходу</th>
            <th>Ціна</th>
            <th>Кільк.сторінок</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var book in Model)
        {
            <tr>
                <td>@book.Title</td>
                <td>@book.Author.Name</td>
                <td>@book.Ganr.Name</td>
                <td>@book.DateTime.ToString("dd.MM.yyyy")</td>
                <td>@book.Price</td>
                <td>@book.Pages</td>
                <td>
                    <a class="btn btn-warning" href="@Url.Action("Edit", "Book", new { id = book.Id })">Edit</a> |
                    <a class="btn btn-danger" href="@Url.Action("Delete", "Book", new { id = book.Id,Temp=@ViewBag.SearchMessage })">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@{
    if (Model.Count() == 0)
    {
            <h3>Не має жодної книги</h3>
    }
}